# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dnsee < Formula
  desc "Check DNS configurations quickly"
  homepage "https://github.com/bschaatsbergen/dnsee"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bschaatsbergen/dnsee/releases/download/v0.1.0/dnsee_0.1.0_darwin_amd64.tar.gz"
      sha256 "58db222fe2d12f6d80be5dbb7c7a44111829dce2e8ac79eb3718237a4b2fa39c"

      def install
        bin.install "dnsee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bschaatsbergen/dnsee/releases/download/v0.1.0/dnsee_0.1.0_darwin_arm64.tar.gz"
      sha256 "8041dff965c68ccaf8a6d9f4d95232f91c461ec6763ce63f78ca3302b6b662a2"

      def install
        bin.install "dnsee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bschaatsbergen/dnsee/releases/download/v0.1.0/dnsee_0.1.0_linux_amd64.tar.gz"
      sha256 "275e60041b47b07a35cc38f9b098f9395edada9e75db83c72d9eb7204a6d25dc"

      def install
        bin.install "dnsee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bschaatsbergen/dnsee/releases/download/v0.1.0/dnsee_0.1.0_linux_arm64.tar.gz"
      sha256 "5cf215b2840b1f6925eab3cd335a5d03ad32a24fddc7997cf7afe8d5c3828996"

      def install
        bin.install "dnsee"
      end
    end
  end

  test do
    system "#{bin}/dnsee -v"
  end
end
